### PR TITLE
Subject encoding fix

### PR DESCRIPTION
**Pull request by shisrafilov**
There is an issue with encoding of email's subject - https://github.com/lasselindqvist/robotframework-imaplibrary2/issues/24

### CODE REVIEW

**Comment by lasselindqvist** [comment]
Can you squash all the commits into one?
How did you test this change?

**Comment by shisrafilov** [comment]
> Can you squash all the commits into one? 

I'll try.
> How did you test this change?

We use emails with different languages on our project and it works.

**Comment by shisrafilov** [comment]
@lasselindqvist what do you think?

**Comment by lasselindqvist** [comment]
Squashing did not go as planned, but I will do a Squash-merge. I will try to see if I can release this already today or at least this week.

**Comment by shisrafilov** [comment]
Thanks in advance!

**Pull request merged**
